# Imports

In [38]:
import aurorax
import os
import pprint
import pandas as pd

# Get all data sources

In [5]:
# get sources
sources = aurorax.sources.list()

# show as a pandas dataframe
df = pd.DataFrame(sources["data"])
df.sort_values(["program", "platform"])

     identifier   program    platform instrument_type source_type display_name
121          23       ace         ace         ssc-web         heo          ACE
127          24    active      active         ssc-web         heo       Active
131          25  aerocube  aerocube6a         ssc-web         heo  AEROCUBE-6a
140          26  aerocube  aerocube6b         ssc-web         heo  AEROCUBE-6b
149          27       aim         aim         ssc-web         leo          AIM
..          ...       ...         ...             ...         ...          ...
188         317      uars        uars         ssc-web         leo         UARS
193         322    viking      viking         ssc-web         heo       Viking
194         323      wind        wind         ssc-web         heo         Wind
195         324       xmm         xmm         ssc-web         heo   XMM-Newton
196         325    yohkoh      yohkoh         ssc-web         leo       Yohkoh

[272 rows x 6 columns]

# Get all THEMIS ASI data sources

In [6]:
# get sources
sources = aurorax.sources.get_using_filters(program="themis-asi")

# show as a pandas dataframe
df = pd.DataFrame(sources["data"])
df.sort_values(["program", "platform"])

,identifier,program,platform,instrument_type,source_type,display_name
1,163,themis-asi,athabasca,panchromatic ASI,ground,THEMIS-ASI ATHA
2,164,themis-asi,chibougamau,panchromatic ASI,ground,THEMIS-ASI CHBG
3,165,themis-asi,ekati,panchromatic ASI,ground,THEMIS-ASI EKAT
4,166,themis-asi,fort simpson,panchromatic ASI,ground,THEMIS-ASI FSIM
5,167,themis-asi,fort smith,panchromatic ASI,ground,THEMIS-ASI FSMI
6,168,themis-asi,fort yukon,panchromatic ASI,ground,THEMIS-ASI FYKN
7,169,themis-asi,gakona,panchromatic ASI,ground,THEMIS-ASI GAKO
0,161,themis-asi,gillam,panchromatic ASI,ground,THEMIS-ASI GILL
8,170,themis-asi,goose bay,panchromatic ASI,ground,THEMIS-ASI GBAY
9,171,themis-asi,inuvik,panchromatic ASI,ground,THEMIS-ASI INUV
10,172,themis-asi,kapuskasing,panchromatic ASI,ground,THEMIS-ASI KAPU
11,173,themis-asi,kiana,panchromatic ASI,ground,THEMIS-ASI KIAN
12,174,themis-asi,kuujjuaq,panchromatic ASI,ground,THEMIS-ASI KUUJ
13,175,themis-asi,mcgrath,panchromatic ASI,ground,THEMIS-ASI MCGR
14,176,themis-asi,narsarsuaq,panchromatic ASI,ground,THEMIS-ASI NRSQ
16,178,themis-asi,pinawa,panchromatic ASI,ground,THEMIS-ASI PINA
15,177,themis-asi,prince george,panchromatic ASI,ground,THEMIS-ASI PGEO
17,179,themis-asi,rankin inlet,panchromatic ASI,ground,THEMIS-ASI RANK
19,181,themis-asi,sanikiluaq,panchromatic ASI,ground,THEMIS-ASI SNKQ
18,180,themis-asi,snap lake,panchromatic ASI,ground,THEMIS-ASI SNAP
20,182,themis-asi,taloyoak,panchromatic ASI,ground,THEMIS-ASI TALO
21,183,themis-asi,the pas,panchromatic ASI,ground,THEMIS-ASI TPAS
22,184,themis-asi,whitehorse,panchromatic ASI,ground,THEMIS-ASI WHIT
23,185,themis-asi,yellowknife,panchromatic ASI,ground,THEMIS-ASI YKNF

# Get all RGB instrument types

In [7]:
# get sources
sources = aurorax.sources.get_using_filters(instrument_type="RGB ASI")

# show as a pandas dataframe
df = pd.DataFrame(sources["data"])
df.sort_values(["program", "platform"])

,identifier,program,platform,instrument_type,source_type,display_name
0,210,rainbow,athabasca,RGB ASI,ground,Rainbow ATHA
1,211,rainbow,fort simpson,RGB ASI,ground,Rainbow FSIM
2,212,rainbow,fort smith,RGB ASI,ground,Rainbow FSMI
3,213,rainbow,gillam,RGB ASI,ground,Rainbow GILL
4,214,rainbow,pinawa,RGB ASI,ground,Rainbow PINA
5,215,rainbow,rabbit lake,RGB ASI,ground,Rainbow RABB
11,333,rainbow,resolute bay,RGB ASI,ground,Rainbow RESU
12,334,rainbow,saskatoon,RGB ASI,ground,Rainbow SASK
13,335,rainbow,yellowknife,RGB ASI,ground,Rainbow YKNF
6,294,trex,fort smith,RGB ASI,ground,TREx RGB FSMI
7,295,trex,gillam,RGB ASI,ground,TREx RGB GILL
8,296,trex,lucky lake,RGB ASI,ground,TREx RGB LUCK
9,297,trex,pinawa,RGB ASI,ground,TREx RGB PINA
10,298,trex,rabbit lake,RGB ASI,ground,TREx RGB RABB

# Get all Swarm data sources

In [9]:
# get sources
sources = aurorax.sources.get_using_filters(program="swarm")

# show as a pandas dataframe
df = pd.DataFrame(sources["data"])
df.sort_values(["program", "platform", "instrument_type"])

   identifier program platform     instrument_type source_type display_name
0           3   swarm   swarma             ssc-web         leo      Swarm A
1         319   swarm   swarma  thermal ion imager         leo  Swarm A TII
4           4   swarm   swarmb             ssc-web         leo      Swarm B
2         320   swarm   swarmb  thermal ion imager         leo  Swarm B TII
5           5   swarm   swarmc             ssc-web         leo      Swarm C
3         321   swarm   swarmc  thermal ion imager         leo  Swarm C TII

# Get all low-earth orbit data sources (LEO)

In [10]:
# source type options are "leo", "heo", "ground", or "lunar"
sources = aurorax.sources.get_using_filters(source_type="leo")

# show as a pandas dataframe
df = pd.DataFrame(sources["data"])
df.sort_values(["program", "platform"])

     identifier   program   platform instrument_type source_type display_name
62           27       aim        aim         ssc-web         leo          AIM
63           29  alouette  alouette1         ssc-web         leo    Alouette1
65           30  alouette  alouette2         ssc-web         leo    Alouette2
109          61      aqua       aqua         ssc-web         leo         Aqua
110          66     ariel     ariel4         ssc-web         leo      ARIEL-4
..          ...       ...        ...             ...         ...          ...
99            5     swarm     swarmc         ssc-web         leo      Swarm C
60          266   tatiana   tatiana1         ssc-web         leo     Tatiana1
61          267   tatiana   tatiana2         ssc-web         leo     Tatiana2
74          317      uars       uars         ssc-web         leo         UARS
79          325    yohkoh     yohkoh         ssc-web         leo       Yohkoh

[128 rows x 6 columns]

# Determine the identifier for a data source

In [11]:
sources = aurorax.sources.get_using_filters(program="swarm",
                                            platform="swarma",
                                            instrument_type="ssc-web")
identifier = sources["data"][0]["identifier"]
print("Identifier: %d" % (identifier))

Identifier: 3

# Get data source using identifier

In [16]:
# get source
source = aurorax.sources.get_using_identifier(3)
pprint.pprint(source)

{'data': {'display_name': 'Swarm A',
          'identifier': 3,
          'instrument_type': 'ssc-web',
          'platform': 'swarma',
          'program': 'swarm',
          'source_type': 'leo'},
 'status_code': 200}

# Get data source information with different levels of information

Both the get_using_identifier() and get_using_filters() methods allow the "format" parameter. The available format options are: identifier_only, basic_info, full_record

In [30]:
# less information
source = aurorax.sources.get_using_filters(program="swarm",
                                           platform="swarma", 
                                           instrument_type="ssc-web", 
                                           format="identifier_only")
# show as a pandas dataframe
df = pd.DataFrame(source["data"])
df

   identifier
0           3

In [32]:
# default information
source = aurorax.sources.get_using_identifier(3, format="basic_info")

# show as a pandas dataframe
df = pd.DataFrame([source["data"]])
df

   identifier program platform instrument_type source_type display_name
0           3   swarm   swarma         ssc-web         leo      Swarm A

In [33]:
# more information
source = aurorax.sources.get_using_identifier(3, format="full_record")

# show as a pandas dataframe
df = pd.DataFrame([source["data"]])
df

,identifier,program,platform,instrument_type,source_type,display_name,owner,maintainers,ephemeris_metadata_schema,data_product_metadata_schema
0,3,swarm,swarma,ssc-web,leo,Swarm A,dchaddoc@ucalgary.ca,[],"[{'field_name': 'nbtrace_region', 'description...",[]

# Get statistics for a data source

In [34]:
# set parameters and get identifier
program = "themis"
platform = "themise"
instrument_type = "ssc-web"
data_source = aurorax.sources.get_using_filters(program=program,
                                                platform=platform,
                                                instrument_type=instrument_type)
identifier = data_source["data"][0]["identifier"]

In [35]:
# get statistics
print("Retrieving statistics for '%s, %s, %s' ...\n" % (program, platform, instrument_type))
stats = aurorax.sources.get_stats(identifier)
pprint.pprint(stats)

Retrieving statistics for 'themis, themise, ssc-web' ...

{'data': {'data_product_count': 0,
          'data_source': {'display_name': 'THEMIS-E',
                          'identifier': 10,
                          'instrument_type': 'ssc-web',
                          'platform': 'themise',
                          'program': 'themis',
                          'source_type': 'heo'},
          'earliest_data_source_loaded': None,
          'earliest_ephemeris_loaded': '2007-02-18T00:14:00',
          'ephemeris_count': 7295026,
          'latest_data_source_loaded': None,
          'latest_ephemeris_loaded': '2020-12-31T23:59:00'},
 'status_code': 200}

# Add a new data source

In [39]:
# read API key from environment vars
api_key = os.environ["AURORAX_API_KEY"]

In [42]:
# set values
program = "notebook-program"
platform = "notebook-platform"
instrument_type = "notebook-instrument-type"
source_type = "ground"
display_name = "Notebook Test Instrument"
metadata_schema_ephemeris = [
    {
        "field_name": "test_meta1",
        "description": "testing metadata field 1",
        "data_type": "string",
        "allowed_values": [],
    },
    {
        "field_name": "test_meta2",
        "description": "testing metadata field 2",
        "data_type": "string",
        "allowed_values": [],
    }
]
metadata_schema_data_products = [
    {
        "field_name": "test_meta1",
        "description": "testing metadata field 1",
        "data_type": "string",
        "allowed_values": [],
    },
    {
        "field_name": "test_meta2",
        "description": "testing metadata field 2",
        "data_type": "string",
        "allowed_values": [],
    }
]

In [45]:
# add source
r = aurorax.sources.add(api_key,
                        program,
                        platform,
                        instrument_type,
                        source_type,
                        display_name,
                        ephemeris_metadata_schema=metadata_schema_ephemeris,
                        data_products_metadata_schema=metadata_schema_data_products)

In [47]:
# check to see if it was successful
if (r["status_code"] == 200):
    print("Successfully added source\n")
else:
    print("Error adding source\n")
pprint.pprint(r)

Successfully added source

{'data': {'display_name': 'Notebook Test Instrument',
          'identifier': 356,
          'instrument_type': 'notebook-instrument-type',
          'platform': 'notebook-platform',
          'program': 'notebook-program',
          'source_type': 'ground'},
 'status_code': 200}