# Imports

In [2]:
import aurorax
import datetime
import pandas as pd
import pprint

# Search

In [3]:
# set values
start_dt = datetime.datetime(2019, 1, 1, 0, 0, 0)
end_dt = datetime.datetime(2019, 1, 1, 23, 59, 59)
programs = ["swarm"]
platforms = ["swarma"]
instrument_types = ["footprint"]

In [4]:
# perform search
s = aurorax.ephemeris.search(start_dt,
                             end_dt,
                             programs=programs,
                             platforms=platforms,
                             instrument_types=instrument_types,
                             verbose=True)

[2021-02-26 02:36:25.415804] Search object created
[2021-02-26 02:36:25.481851] Request submitted
[2021-02-26 02:36:25.481947] Request ID: 213a0c75-4e00-4218-92c4-65a02904e2e6
[2021-02-26 02:36:25.481989] Request details available at: http://api.aurorax.space/api/v1/ephemeris/requests/213a0c75-4e00-4218-92c4-65a02904e2e6
[2021-02-26 02:36:25.482027] Waiting for data ...
[2021-02-26 02:36:26.613802] Checking for data ...
[2021-02-26 02:36:26.708297] Data is now available
[2021-02-26 02:36:26.708397] Retrieving data ...
[2021-02-26 02:36:27.568078] Retrieved 5.1 MB of data containing 1440 records

In [6]:
# output data as a pandas dataframe
df = pd.DataFrame(s.data)
df.sort_values("epoch")  # sort by the timestamp

,data_source,epoch,location_geo,location_gsm,nbtrace,sbtrace,metadata
0,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:00:00,"{'lat': -17.019026, 'lon': -136.0207}","{'lat': 6.7606134, 'lon': 40.40137}","{'lat': 14.933351, 'lon': -130.16835}","{'lat': -21.815926, 'lon': -137.23001}","{'state': 'definitive', 'nbtrace_region': 'low..."
1,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:01:00,"{'lat': -13.168878, 'lon': -136.07999}","{'lat': 10.541506, 'lon': 41.12732}","{'lat': 12.554154, 'lon': -131.52226}","{'lat': -19.18973, 'lon': -137.46463}","{'state': 'definitive', 'nbtrace_region': 'low..."
2,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:02:00,"{'lat': -9.317859, 'lon': -136.14517}","{'lat': 14.321112, 'lon': 41.87248}","{'lat': 10.6922245, 'lon': -132.69847}","{'lat': -17.108786, 'lon': -137.80627}","{'state': 'definitive', 'nbtrace_region': 'low..."
3,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:03:00,"{'lat': -5.466018, 'lon': -136.21439}","{'lat': 18.098713, 'lon': 42.64437}","{'lat': 9.6191, 'lon': -133.67313}","{'lat': -15.831487, 'lon': -138.30301}","{'state': 'definitive', 'nbtrace_region': 'low..."
4,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:04:00,"{'lat': -1.6134088, 'lon': -136.2859}","{'lat': 21.873484, 'lon': 43.451508}","{'lat': 9.573847, 'lon': -134.42802}","{'lat': -15.586076, 'lon': -139.00354}","{'state': 'definitive', 'nbtrace_region': 'low..."
...,...,...,...,...,...,...,...
1435,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:55:00,"{'lat': 63.118088, 'lon': 39.44719}","{'lat': 38.491505, 'lon': -150.19873}","{'lat': 63.825092, 'lon': 39.852196}","{'lat': -52.62199, 'lon': 65.487434}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1436,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:56:00,"{'lat': 59.271484, 'lon': 39.970604}","{'lat': 34.721504, 'lon': -149.17068}","{'lat': 60.096794, 'lon': 40.335415}","{'lat': -48.855095, 'lon': 61.44911}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1437,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:57:00,"{'lat': 55.42148, 'lon': 40.336536}","{'lat': 30.944128, 'lon': -148.23186}","{'lat': 56.37933, 'lon': 40.665756}","{'lat': -44.895798, 'lon': 57.84364}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1438,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:58:00,"{'lat': 51.569214, 'lon': 40.592674}","{'lat': 27.161028, 'lon': -147.36389}","{'lat': 52.677044, 'lon': 40.891216}","{'lat': -40.812534, 'lon': 54.591457}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1439,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:59:00,"{'lat': 47.715435, 'lon': 40.76942}","{'lat': 23.373522, 'lon': -146.55217}","{'lat': 48.9952, 'lon': 41.04236}","{'lat': -36.66003, 'lon': 51.658134}","{'state': 'definitive', 'nbtrace_region': 'nor..."

# Do the search asynchonously

Under the hood an ephemeris search is asynchronous. This adds some more complexity for the user, but also opens the search up to some additional possibilities. The main advantage is being able to perform queries for a large timeframe. These queries will take a bit longer and could exceed several minutes and return more than a gigabyte of data. Separating the request and the resulting data into two different API calls allows flexibility in duration and size of the overall request.

In [14]:
# set up the request
s = aurorax.ephemeris.Search(start_dt,
                             end_dt,
                             programs=programs,
                             platforms=platforms,
                             instrument_types=instrument_types)
print(s)

{'completed': False,
 'data': [],
 'data_url': '',
 'end_dt': datetime.datetime(2019, 1, 1, 23, 59, 59),
 'executed': False,
 'instrument_types': ['footprint'],
 'logs': [],
 'metadata_filters': [],
 'platforms': ['swarma'],
 'programs': ['swarm'],
 'query': {},
 'request': None,
 'request_id': '',
 'request_url': '',
 'start_dt': datetime.datetime(2019, 1, 1, 0, 0),
 'status': {}}

In [15]:
# execute the search
s.execute()
print(s)

{'completed': False,
 'data': [],
 'data_url': '',
 'end_dt': datetime.datetime(2019, 1, 1, 23, 59, 59),
 'executed': True,
 'instrument_types': ['footprint'],
 'logs': [],
 'metadata_filters': [],
 'platforms': ['swarma'],
 'programs': ['swarm'],
 'query': {'data_sources': {'ephemeris_metadata_filters': [],
                            'instrument_types': ['footprint'],
                            'platforms': ['swarma'],
                            'programs': ['swarm']},
           'end': '2019-01-01T23:59:59',
           'start': '2019-01-01T00:00:00'},
 'request': {'data': None, 'request': <Response [202]>, 'status_code': 202},
 'request_id': '9fd7113b-c01b-4de9-8be8-c230a165ac4c',
 'request_url': 'http://api.aurorax.space/api/v1/ephemeris/requests/9fd7113b-c01b-4de9-8be8-c230a165ac4c',
 'start_dt': datetime.datetime(2019, 1, 1, 0, 0),
 'status': {}}

In [16]:
# get request status
s.update_status()
pprint.pprint(s.status)

{'logs': [{'level': 'debug',
           'summary': 'Search request arrived',
           'timestamp': '2021-02-26T02:40:57.257594Z'},
          {'level': 'debug',
           'summary': 'Starting 9fd7113b-c01b-4de9-8be8-c230a165ac4c for query '
                      'Find ephemeris for (program in (swarm) AND platform in '
                      '(swarma) AND instrument_type in (footprint) AND )  AND '
                      'epoch between 2019-01-01T00:00 and 2019-01-01T23:59:59 '
                      'UTC',
           'timestamp': '2021-02-26T02:40:57.259754Z'},
          {'level': 'info',
           'summary': 'Finished query in 0.02 seconds.',
           'timestamp': '2021-02-26T02:40:57.277966Z'},
          {'level': 'debug',
           'summary': 'Starting to write data to file',
           'timestamp': '2021-02-26T02:40:57.278963Z'},
          {'level': 'info',
           'summary': 'Finished writing data, found 1440 records in 0.29 '
                      'seconds.',
           'timestamp': '2021-02-26T02:40:57.566946Z'},
          {'level': 'debug',
           'summary': 'File size is 5137225 bytes.',
           'timestamp': '2021-02-26T02:40:57.568991Z'},
          {'level': 'info',
           'summary': 'Finished search in 0.31 seconds and found 1440 records.',
           'timestamp': '2021-02-26T02:40:57.571463Z'}],
 'search_request': {'query': {'data_sources': {'ephemeris_metadata_filters': [],
                                               'instrument_types': ['footprint'],
                                               'platforms': ['swarma'],
                                               'programs': ['swarm']},
                              'end': '2019-01-01T23:59:59',
                              'start': '2019-01-01T00:00:00'},
                    'request_id': '9fd7113b-c01b-4de9-8be8-c230a165ac4c',
                    'request_type': 'ephemeris',
                    'requested': '2021-02-26T02:40:57.254276Z',
                    'user_uuid': None},
 'search_result': {'completed_timestamp': '2021-02-26T02:40:57.570112Z',
                   'data_uri': '/api/v1/ephemeris/requests/9fd7113b-c01b-4de9-8be8-c230a165ac4c/data',
                   'error_condition': False,
                   'expiration_timestamp': '2021-03-03T02:40:57.569052Z',
                   'file_size': 5137225,
                   'query_duration': 310,
                   'result_count': 1440,
                   'result_file_deleted_timestamp': None}}

In [17]:
# view just the logs for the request (update the status beforehand, but we do that in the above cell)
pprint.pprint(s.logs)

[{'level': 'debug',
  'summary': 'Search request arrived',
  'timestamp': '2021-02-26T02:40:57.257594Z'},
 {'level': 'debug',
  'summary': 'Starting 9fd7113b-c01b-4de9-8be8-c230a165ac4c for query Find '
             'ephemeris for (program in (swarm) AND platform in (swarma) AND '
             'instrument_type in (footprint) AND )  AND epoch between '
             '2019-01-01T00:00 and 2019-01-01T23:59:59 UTC',
  'timestamp': '2021-02-26T02:40:57.259754Z'},
 {'level': 'info',
  'summary': 'Finished query in 0.02 seconds.',
  'timestamp': '2021-02-26T02:40:57.277966Z'},
 {'level': 'debug',
  'summary': 'Starting to write data to file',
  'timestamp': '2021-02-26T02:40:57.278963Z'},
 {'level': 'info',
  'summary': 'Finished writing data, found 1440 records in 0.29 seconds.',
  'timestamp': '2021-02-26T02:40:57.566946Z'},
 {'level': 'debug',
  'summary': 'File size is 5137225 bytes.',
  'timestamp': '2021-02-26T02:40:57.568991Z'},
 {'level': 'info',
  'summary': 'Finished search in 0.31 seconds and found 1440 records.',
  'timestamp': '2021-02-26T02:40:57.571463Z'}]

In [18]:
# wait for the data
s.wait()
s.update_status()

In [19]:
# get data
s.get_data()

# show data as pandas dataframe
df = pd.DataFrame(s.data)
df.sort_values("epoch")  # sort by the timestamp

,data_source,epoch,location_geo,location_gsm,nbtrace,sbtrace,metadata
0,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:00:00,"{'lat': -17.019026, 'lon': -136.0207}","{'lat': 6.7606134, 'lon': 40.40137}","{'lat': 14.933351, 'lon': -130.16835}","{'lat': -21.815926, 'lon': -137.23001}","{'state': 'definitive', 'nbtrace_region': 'low..."
1,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:01:00,"{'lat': -13.168878, 'lon': -136.07999}","{'lat': 10.541506, 'lon': 41.12732}","{'lat': 12.554154, 'lon': -131.52226}","{'lat': -19.18973, 'lon': -137.46463}","{'state': 'definitive', 'nbtrace_region': 'low..."
2,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:02:00,"{'lat': -9.317859, 'lon': -136.14517}","{'lat': 14.321112, 'lon': 41.87248}","{'lat': 10.6922245, 'lon': -132.69847}","{'lat': -17.108786, 'lon': -137.80627}","{'state': 'definitive', 'nbtrace_region': 'low..."
3,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:03:00,"{'lat': -5.466018, 'lon': -136.21439}","{'lat': 18.098713, 'lon': 42.64437}","{'lat': 9.6191, 'lon': -133.67313}","{'lat': -15.831487, 'lon': -138.30301}","{'state': 'definitive', 'nbtrace_region': 'low..."
4,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 00:04:00,"{'lat': -1.6134088, 'lon': -136.2859}","{'lat': 21.873484, 'lon': 43.451508}","{'lat': 9.573847, 'lon': -134.42802}","{'lat': -15.586076, 'lon': -139.00354}","{'state': 'definitive', 'nbtrace_region': 'low..."
...,...,...,...,...,...,...,...
1435,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:55:00,"{'lat': 63.118088, 'lon': 39.44719}","{'lat': 38.491505, 'lon': -150.19873}","{'lat': 63.825092, 'lon': 39.852196}","{'lat': -52.62199, 'lon': 65.487434}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1436,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:56:00,"{'lat': 59.271484, 'lon': 39.970604}","{'lat': 34.721504, 'lon': -149.17068}","{'lat': 60.096794, 'lon': 40.335415}","{'lat': -48.855095, 'lon': 61.44911}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1437,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:57:00,"{'lat': 55.42148, 'lon': 40.336536}","{'lat': 30.944128, 'lon': -148.23186}","{'lat': 56.37933, 'lon': 40.665756}","{'lat': -44.895798, 'lon': 57.84364}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1438,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:58:00,"{'lat': 51.569214, 'lon': 40.592674}","{'lat': 27.161028, 'lon': -147.36389}","{'lat': 52.677044, 'lon': 40.891216}","{'lat': -40.812534, 'lon': 54.591457}","{'state': 'definitive', 'nbtrace_region': 'nor..."
1439,"{'identifier': 3, 'program': 'swarm', 'platfor...",2019-01-01 23:59:00,"{'lat': 47.715435, 'lon': 40.76942}","{'lat': 23.373522, 'lon': -146.55217}","{'lat': 48.9952, 'lon': 41.04236}","{'lat': -36.66003, 'lon': 51.658134}","{'state': 'definitive', 'nbtrace_region': 'nor..."