# Imports

In [1]:
import pyaurorax
import datetime
import pprint
import pandas as pd

# Search for ephemeris records

In [2]:
# set values
start = datetime.datetime(2019, 1, 1, 0, 0, 0)
end = datetime.datetime(2019, 1, 1, 23, 59, 59)
programs = ["swarm"]
platforms = ["swarma"]
instrument_types = ["footprint"]

In [3]:
# perform search
s = pyaurorax.ephemeris.search(start,
                               end,
                               programs=programs,
                               platforms=platforms,
                               instrument_types=instrument_types,
                               verbose=True)

[2022-01-14 01:38:06.131864] Search object created
[2022-01-14 01:38:06.215829] Request submitted
[2022-01-14 01:38:06.215962] Request ID: 866d4c03-edea-4f83-8f6a-37640d1df106
[2022-01-14 01:38:06.215976] Request details available at: https://api.aurorax.space/api/v1/ephemeris/requests/866d4c03-edea-4f83-8f6a-37640d1df106
[2022-01-14 01:38:06.215983] Waiting for data ...
[2022-01-14 01:38:07.279938] Checking for data ...
[2022-01-14 01:38:07.384325] Data is now available
[2022-01-14 01:38:07.385172] Retrieving data ...
[2022-01-14 01:38:08.279066] Retrieved 8.2 MB of data containing 1440 records

In [4]:
# output data as a pandas dataframe
ephemeris_data = [e.__dict__ for e in s.data]
df = pd.DataFrame(ephemeris_data)
df.sort_values("epoch")  # sort by the timestamp

,data_source,epoch,location_geo,location_gsm,nbtrace,sbtrace,metadata
0,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:00:00,"Location(lat=-17.019026, lon=-136.0207)","Location(lat=-17.019026, lon=-136.0207)","Location(lat=14.933351, lon=-130.16835)","Location(lat=-21.815926, lon=-137.23001)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
1,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:01:00,"Location(lat=-13.168878, lon=-136.07999)","Location(lat=-13.168878, lon=-136.07999)","Location(lat=12.554154, lon=-131.52226)","Location(lat=-19.18973, lon=-137.46463)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
2,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:02:00,"Location(lat=-9.317859, lon=-136.14517)","Location(lat=-9.317859, lon=-136.14517)","Location(lat=10.6922245, lon=-132.69847)","Location(lat=-17.108786, lon=-137.80627)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
3,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:03:00,"Location(lat=-5.466018, lon=-136.21439)","Location(lat=-5.466018, lon=-136.21439)","Location(lat=9.6191, lon=-133.67313)","Location(lat=-15.831487, lon=-138.30301)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
4,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:04:00,"Location(lat=-1.6134088, lon=-136.2859)","Location(lat=-1.6134088, lon=-136.2859)","Location(lat=9.573847, lon=-134.42802)","Location(lat=-15.586076, lon=-139.00354)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
...,...,...,...,...,...,...,...
1435,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:55:00,"Location(lat=63.118088, lon=39.44719)","Location(lat=63.118088, lon=39.44719)","Location(lat=63.825092, lon=39.852196)","Location(lat=-52.62199, lon=65.487434)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1436,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:56:00,"Location(lat=59.271484, lon=39.970604)","Location(lat=59.271484, lon=39.970604)","Location(lat=60.096794, lon=40.335415)","Location(lat=-48.855095, lon=61.44911)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1437,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:57:00,"Location(lat=55.42148, lon=40.336536)","Location(lat=55.42148, lon=40.336536)","Location(lat=56.37933, lon=40.665756)","Location(lat=-44.895798, lon=57.84364)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1438,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:58:00,"Location(lat=51.569214, lon=40.592674)","Location(lat=51.569214, lon=40.592674)","Location(lat=52.677044, lon=40.891216)","Location(lat=-40.812534, lon=54.591457)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1439,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:59:00,"Location(lat=47.715435, lon=40.76942)","Location(lat=47.715435, lon=40.76942)","Location(lat=48.9952, lon=41.04236)","Location(lat=-36.66003, lon=51.658134)","{'state': 'definitive', 'nbtrace_region': 'nor..."

# Do the search step-by-step

Under the hood, the AuroraX API performs an ephemeris search asynchronously. Note that this does not mean that it can be done using a Python async method; it means that PyAuroraX does more than just a single HTTP request against the AuroraX API when doing a search. With the API operating this way, it adds some more complexity within PyAuroraX but also opens the search up to some very important capabilities. The main capability enabled by this architecture is the ablity to perform queries for a large timeframe, and/or for a large number of data sources. Queries like this can easily take several minutes, and can return hundreds of megabytes - or eve gigabytes - of data. A conventional HTTP request would normally timeout because of this, ultimately failing to complete the search.

Instead of using the `pyaurorax.ephemeris.search` method which wraps all logic into an easy function, you can also perform an ephemeris search step-by-step if you want more control over the process. Below, we do a search in this manner.

In [5]:
# set up search parameters
start = datetime.datetime(2019, 1, 1, 0, 0, 0)
end = datetime.datetime(2019, 1, 1, 23, 59, 59)
programs = ["swarm"]
platforms = ["swarma"]
instrument_types = ["footprint"]

In [6]:
# create the Search object
s = pyaurorax.ephemeris.Search(start,
                               end,
                               programs=programs,
                               platforms=platforms,
                               instrument_types=instrument_types)
print(s)

EphemerisSearch(executed=False, completed=False, request_id='')

In [7]:
# execute the search
s.execute()
print(s)

EphemerisSearch(executed=True, completed=False, request_id='af980313-92a2-4ec4-9aaf-c9357ccde26a')

In [8]:
# get request status
s.update_status()
pprint.pprint(s.status)

{'logs': [{'level': 'debug',
           'summary': 'Search request arrived and saved',
           'timestamp': '2022-01-14T01:39:57.746673Z'},
          {'level': 'debug',
           'summary': 'Starting af980313-92a2-4ec4-9aaf-c9357ccde26a for query '
                      'Find ephemeris for ((program in (swarm) AND platform in '
                      '(swarma) AND instrument_type in (footprint) filtered by '
                      'metadata ()) AND  ephemeris_metadata_filters [])  AND '
                      'epoch between 2019-01-01T00:00 and 2019-01-01T23:59:59 '
                      'UTC',
           'timestamp': '2022-01-14T01:39:57.760113Z'},
          {'level': 'info',
           'summary': 'Finished query in 0.02 seconds.',
           'timestamp': '2022-01-14T01:39:57.784864Z'},
          {'level': 'debug',
           'summary': 'Starting to write data to file',
           'timestamp': '2022-01-14T01:39:57.799244Z'},
          {'level': 'info',
           'summary': 'Finished writing data, found 1440 records in 0.43 '
                      'seconds.',
           'timestamp': '2022-01-14T01:39:58.239025Z'},
          {'level': 'debug',
           'summary': 'File size is 8241995 bytes.',
           'timestamp': '2022-01-14T01:39:58.251103Z'},
          {'level': 'info',
           'summary': 'Finished search in 0.51 seconds and found 1440 records.',
           'timestamp': '2022-01-14T01:39:58.274023Z'}],
 'search_request': {'query': {'data_sources': {'ephemeris_metadata_filters': {'expressions': [],
                                                                              'logical_operator': 'AND'},
                                               'instrument_types': ['footprint'],
                                               'platforms': ['swarma'],
                                               'programs': ['swarm']},
                              'end': '2019-01-01T23:59:59',
                              'request_id': 'af980313-92a2-4ec4-9aaf-c9357ccde26a',
                              'start': '2019-01-01T00:00:00'},
                    'request_id': 'af980313-92a2-4ec4-9aaf-c9357ccde26a',
                    'request_type': 'ephemeris',
                    'requested': '2022-01-14T01:39:57.726201Z'},
 'search_result': {'completed_timestamp': '2022-01-14T01:39:58.264978Z',
                   'data_uri': '/api/v1/ephemeris/requests/af980313-92a2-4ec4-9aaf-c9357ccde26a/data',
                   'error_condition': False,
                   'file_size': 8241995,
                   'query_duration': 505,
                   'result_count': 1440,
                   'result_file_deleted_timestamp': None}}

In [9]:
# view just the logs for the request (update the status beforehand, but we do that in the above cell)
pprint.pprint(s.logs)

[{'level': 'debug',
  'summary': 'Search request arrived and saved',
  'timestamp': '2022-01-14T01:39:57.746673Z'},
 {'level': 'debug',
  'summary': 'Starting af980313-92a2-4ec4-9aaf-c9357ccde26a for query Find '
             'ephemeris for ((program in (swarm) AND platform in (swarma) AND '
             'instrument_type in (footprint) filtered by metadata ()) AND  '
             'ephemeris_metadata_filters [])  AND epoch between '
             '2019-01-01T00:00 and 2019-01-01T23:59:59 UTC',
  'timestamp': '2022-01-14T01:39:57.760113Z'},
 {'level': 'info',
  'summary': 'Finished query in 0.02 seconds.',
  'timestamp': '2022-01-14T01:39:57.784864Z'},
 {'level': 'debug',
  'summary': 'Starting to write data to file',
  'timestamp': '2022-01-14T01:39:57.799244Z'},
 {'level': 'info',
  'summary': 'Finished writing data, found 1440 records in 0.43 seconds.',
  'timestamp': '2022-01-14T01:39:58.239025Z'},
 {'level': 'debug',
  'summary': 'File size is 8241995 bytes.',
  'timestamp': '2022-01-14T01:39:58.251103Z'},
 {'level': 'info',
  'summary': 'Finished search in 0.51 seconds and found 1440 records.',
  'timestamp': '2022-01-14T01:39:58.274023Z'}]

In [10]:
# wait for the data
s.wait()
s.update_status()

In [12]:
# get data
s.get_data()
print(s.data[0])

# show data as pandas dataframe
ephemeris_data = [e.__dict__ for e in s.data]
df = pd.DataFrame(ephemeris_data)
df.sort_values("epoch")  # sort by the timestamp

Ephemeris(data_source=DataSource(identifier=3, program='swarm', platform='swarma', instrument_type='footprint', source_type='leo', display_name='Swarm A'), epoch=datetime.datetime(2019, 1, 1, 0, 0), location_geo=Location(lat=-17.019026, lon=-136.0207), location_gsm=Location(lat=-17.019026, lon=-136.0207), nbtrace=Location(lat=14.933351, lon=-130.16835), nbtrace=Location(lat=14.933351, lon=-130.16835), metadata={'state': 'definitiv...})

,data_source,epoch,location_geo,location_gsm,nbtrace,sbtrace,metadata
0,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:00:00,"Location(lat=-17.019026, lon=-136.0207)","Location(lat=-17.019026, lon=-136.0207)","Location(lat=14.933351, lon=-130.16835)","Location(lat=-21.815926, lon=-137.23001)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
1,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:01:00,"Location(lat=-13.168878, lon=-136.07999)","Location(lat=-13.168878, lon=-136.07999)","Location(lat=12.554154, lon=-131.52226)","Location(lat=-19.18973, lon=-137.46463)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
2,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:02:00,"Location(lat=-9.317859, lon=-136.14517)","Location(lat=-9.317859, lon=-136.14517)","Location(lat=10.6922245, lon=-132.69847)","Location(lat=-17.108786, lon=-137.80627)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
3,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:03:00,"Location(lat=-5.466018, lon=-136.21439)","Location(lat=-5.466018, lon=-136.21439)","Location(lat=9.6191, lon=-133.67313)","Location(lat=-15.831487, lon=-138.30301)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
4,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 00:04:00,"Location(lat=-1.6134088, lon=-136.2859)","Location(lat=-1.6134088, lon=-136.2859)","Location(lat=9.573847, lon=-134.42802)","Location(lat=-15.586076, lon=-139.00354)","{'state': 'definitive', 'tii_on': True, 'nbtra..."
...,...,...,...,...,...,...,...
1435,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:55:00,"Location(lat=63.118088, lon=39.44719)","Location(lat=63.118088, lon=39.44719)","Location(lat=63.825092, lon=39.852196)","Location(lat=-52.62199, lon=65.487434)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1436,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:56:00,"Location(lat=59.271484, lon=39.970604)","Location(lat=59.271484, lon=39.970604)","Location(lat=60.096794, lon=40.335415)","Location(lat=-48.855095, lon=61.44911)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1437,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:57:00,"Location(lat=55.42148, lon=40.336536)","Location(lat=55.42148, lon=40.336536)","Location(lat=56.37933, lon=40.665756)","Location(lat=-44.895798, lon=57.84364)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1438,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:58:00,"Location(lat=51.569214, lon=40.592674)","Location(lat=51.569214, lon=40.592674)","Location(lat=52.677044, lon=40.891216)","Location(lat=-40.812534, lon=54.591457)","{'state': 'definitive', 'nbtrace_region': 'nor..."
1439,"DataSource(identifier=3, program='swarm', plat...",2019-01-01 23:59:00,"Location(lat=47.715435, lon=40.76942)","Location(lat=47.715435, lon=40.76942)","Location(lat=48.9952, lon=41.04236)","Location(lat=-36.66003, lon=51.658134)","{'state': 'definitive', 'nbtrace_region': 'nor..."