# Imports

In [1]:
import pyaurorax
import datetime
import pandas as pd

# Search

In [2]:
# set values
# search for conjunctions between any THEMIS-ASI intrument and any Swarm instrument
start = datetime.datetime(2020, 1, 1, 0, 0, 0)
end = datetime.datetime(2020, 1, 1, 6, 59, 59)
ground_params = [
    {
        "programs": ["themis-asi"]
    }
]
space_params = [
    {
        "programs": ["swarm"]
    }
]
distance = 100

In [3]:
# perform search
s = pyaurorax.conjunctions.search(start=start,
                               end=end,
                               ground=ground_params,
                               space=space_params,
                               default_distance=distance,
                               verbose=True)

[2021-06-08 15:04:43.315763] Search object created
[2021-06-08 15:04:43.368652] Request submitted
[2021-06-08 15:04:43.368652] Request ID: c84654be-177c-4b6c-a925-9f26162f463c
[2021-06-08 15:04:43.368652] Request details available at: http://api.aurorax.space/api/v1/conjunctions/requests/c84654be-177c-4b6c-a925-9f26162f463c
[2021-06-08 15:04:43.368652] Waiting for data ...
[2021-06-08 15:04:44.455465] Checking for data ...
[2021-06-08 15:04:44.536120] Data is now available
[2021-06-08 15:04:44.536120] Retrieving data ...
[2021-06-08 15:04:44.601821] Retrieved 12.0 kB of data containing 3 records

In [4]:
# output data as a pandas dataframe
conjunctions = [c.__dict__ for c in s.data]
df = pd.DataFrame(conjunctions)
df.sort_values("start")

,conjunction_type,start,end,data_sources,min_distance,max_distance,events
0,nbtrace,2020-01-01 00:12:00,2020-01-01 00:12:00,"[{'data_product_metadata_schema': [],\n 'displ...",89.436436,89.436436,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
1,nbtrace,2020-01-01 00:12:00,2020-01-01 00:12:00,"[{'data_product_metadata_schema': [],\n 'displ...",53.391843,53.391843,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
2,nbtrace,2020-01-01 00:12:00,2020-01-01 00:12:00,"[{'data_product_metadata_schema': [],\n 'displ...",89.436436,89.436436,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."

# Search with metadata filters

In [5]:
# set values
# search for conjunctions between any (THEMIS-ASI or REGO) instrument and (any Swarm instrument 
#  with north B trace region = "north polar cap")
start = datetime.datetime(2019, 2, 1, 0, 0, 0)
end = datetime.datetime(2019, 2, 10, 23, 59, 59)
ground_params = [{
    "programs": ["themis-asi", "rego"]
}]
space_params = [{
    "programs": ["swarm"],
    "ephemeris_metadata_filters": [
        {
            "key": "nbtrace_region",
            "operator": "=",
            "values": [
                "north polar cap"
            ]
        }
    ]
}]

In [6]:
# perform search
s = pyaurorax.conjunctions.search(start=start,
                               end=end,
                               ground=ground_params,
                               space=space_params,
                               default_distance=distance,
                               verbose=True)

[2021-06-08 15:04:44.689415] Search object created
[2021-06-08 15:04:44.729516] Request submitted
[2021-06-08 15:04:44.729516] Request ID: 1effe88e-c77a-4dec-b618-820c0827d42f
[2021-06-08 15:04:44.729516] Request details available at: http://api.aurorax.space/api/v1/conjunctions/requests/1effe88e-c77a-4dec-b618-820c0827d42f
[2021-06-08 15:04:44.729516] Waiting for data ...
[2021-06-08 15:04:45.797167] Checking for data ...
[2021-06-08 15:04:45.885953] Data is now available
[2021-06-08 15:04:45.885953] Retrieving data ...
[2021-06-08 15:04:45.987405] Retrieved 94.7 kB of data containing 16 records

In [7]:
# output data as a pandas dataframe
conjunctions = [c.__dict__ for c in s.data]
df = pd.DataFrame(conjunctions)
df.sort_values("start")

,conjunction_type,start,end,data_sources,min_distance,max_distance,events
10,nbtrace,2019-02-01 08:03:00,2019-02-01 08:03:00,"[{'data_product_metadata_schema': [],\n 'displ...",75.799249,75.799249,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
11,nbtrace,2019-02-01 08:03:00,2019-02-01 08:03:00,"[{'data_product_metadata_schema': [],\n 'displ...",29.624565,29.624565,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
7,nbtrace,2019-02-04 09:11:00,2019-02-04 09:11:00,"[{'data_product_metadata_schema': [],\n 'displ...",98.843249,98.843249,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
8,nbtrace,2019-02-05 02:39:00,2019-02-05 02:39:00,"[{'data_product_metadata_schema': [],\n 'displ...",81.312014,81.312014,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
3,nbtrace,2019-02-05 05:25:00,2019-02-05 05:25:00,"[{'data_product_metadata_schema': [],\n 'displ...",89.645680,89.645680,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
12,nbtrace,2019-02-05 05:25:00,2019-02-05 05:25:00,"[{'data_product_metadata_schema': [],\n 'displ...",89.645680,89.645680,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
5,nbtrace,2019-02-07 01:59:00,2019-02-07 01:59:00,"[{'data_product_metadata_schema': [],\n 'displ...",94.617725,94.617725,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
14,nbtrace,2019-02-07 01:59:00,2019-02-07 01:59:00,"[{'data_product_metadata_schema': [],\n 'displ...",94.617725,94.617725,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
9,nbtrace,2019-02-07 13:11:00,2019-02-07 13:11:00,"[{'data_product_metadata_schema': [],\n 'displ...",90.976970,90.976970,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
0,nbtrace,2019-02-08 08:06:00,2019-02-08 08:06:00,"[{'data_product_metadata_schema': [],\n 'displ...",78.565538,78.565538,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
4,nbtrace,2019-02-10 05:13:00,2019-02-10 05:13:00,"[{'data_product_metadata_schema': [],\n 'displ...",98.464965,98.464965,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
6,nbtrace,2019-02-10 05:13:00,2019-02-10 05:13:00,"[{'data_product_metadata_schema': [],\n 'displ...",32.331145,32.331145,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
13,nbtrace,2019-02-10 05:13:00,2019-02-10 05:13:00,"[{'data_product_metadata_schema': [],\n 'displ...",98.464965,98.464965,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
15,nbtrace,2019-02-10 05:13:00,2019-02-10 05:13:00,"[{'data_product_metadata_schema': [],\n 'displ...",32.331145,32.331145,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
1,nbtrace,2019-02-10 05:15:00,2019-02-10 05:15:00,"[{'data_product_metadata_schema': [],\n 'displ...",67.269683,67.269683,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
2,nbtrace,2019-02-10 05:15:00,2019-02-10 05:15:00,"[{'data_product_metadata_schema': [],\n 'displ...",56.653602,56.653602,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."

# Search with multiple ground and space instruments and custom distances

In [8]:
# set values
# search for conjunctions between any REGO and TREX and Swarm and THEMIS instruments
start = datetime.datetime(2020, 1, 1, 0, 0, 0)
end = datetime.datetime(2020, 1, 4, 23, 59, 59)
ground_params = [
    {
        "programs": ["rego"]
    },
    {
        "programs": ["trex"]
    }
]
space_params = [
    {
        "programs": ["swarm"]
    },
    {
        "programs": ["themis"]
    }
]
distances = {
    "ground1-ground2": None,
    "ground1-space1": 500,
    "ground1-space2": 500,
    "ground2-space1": 500,
    "ground2-space2": 500,
    "space1-space2": None
}

In [9]:
# perform search
s = pyaurorax.conjunctions.search(start=start,
                               end=end,
                               ground=ground_params,
                               space=space_params,
                               default_distance=distance,
                               max_distances=distances,
                               verbose=True)

[2021-06-08 15:04:46.047674] Search object created
[2021-06-08 15:04:46.078941] Request submitted
[2021-06-08 15:04:46.078941] Request ID: 7584aea3-d38a-4c71-8fb2-9f4788758785
[2021-06-08 15:04:46.078941] Request details available at: http://api.aurorax.space/api/v1/conjunctions/requests/7584aea3-d38a-4c71-8fb2-9f4788758785
[2021-06-08 15:04:46.078941] Waiting for data ...
[2021-06-08 15:04:47.149967] Checking for data ...
[2021-06-08 15:04:48.224084] Checking for data ...
[2021-06-08 15:04:49.309718] Checking for data ...
[2021-06-08 15:04:50.397776] Checking for data ...
[2021-06-08 15:04:51.469124] Checking for data ...
[2021-06-08 15:04:51.547210] Data is now available
[2021-06-08 15:04:51.547210] Retrieving data ...
[2021-06-08 15:04:51.654061] Retrieved 123.9 kB of data containing 10 records

In [10]:
# output data as a pandas dataframe
conjunctions = [c.__dict__ for c in s.data]
df = pd.DataFrame(conjunctions)
df.sort_values("start")

,conjunction_type,start,end,data_sources,min_distance,max_distance,events
8,nbtrace,2020-01-02 13:00:00,2020-01-02 13:01:00,"[{'data_product_metadata_schema': [],\n 'displ...",384.347496,440.461162,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
9,nbtrace,2020-01-02 13:00:00,2020-01-02 13:01:00,"[{'data_product_metadata_schema': [],\n 'displ...",384.347496,440.461162,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
1,nbtrace,2020-01-03 12:33:00,2020-01-03 12:35:00,"[{'data_product_metadata_schema': [],\n 'displ...",111.324353,485.848555,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
2,nbtrace,2020-01-03 12:33:00,2020-01-03 12:34:00,"[{'data_product_metadata_schema': [],\n 'displ...",122.118464,294.065540,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
3,nbtrace,2020-01-03 12:33:00,2020-01-03 12:35:00,"[{'data_product_metadata_schema': [],\n 'displ...",111.324353,485.848555,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
4,nbtrace,2020-01-03 12:33:00,2020-01-03 12:34:00,"[{'data_product_metadata_schema': [],\n 'displ...",122.118464,294.065540,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
6,nbtrace,2020-01-03 12:33:00,2020-01-03 12:35:00,"[{'data_product_metadata_schema': [],\n 'displ...",111.324353,485.848555,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
7,nbtrace,2020-01-03 12:33:00,2020-01-03 12:35:00,"[{'data_product_metadata_schema': [],\n 'displ...",111.324353,485.848555,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
0,nbtrace,2020-01-03 12:40:00,2020-01-03 12:42:00,"[{'data_product_metadata_schema': [],\n 'displ...",255.883772,476.507384,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
5,nbtrace,2020-01-03 12:40:00,2020-01-03 12:42:00,"[{'data_product_metadata_schema': [],\n 'displ...",255.883772,476.507384,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."

# Search between space instruments only

In [11]:
# set values
# search for conjunctions between any (Swarm A or Swarm B) instrument 
#  and (any THEMIS instrument with south B trace region = "south polar cap")
start = datetime.datetime(2019, 1, 1, 0, 0, 0)
end = datetime.datetime(2019, 1, 1, 23, 59, 59)
ground_params = []
space_params = [
    {
        "programs": ["swarm"],
        "platforms": ["swarma", "swarmb"],
        "hemisphere": ["southern"],
        "ephemeris_metadata_filters": [
            {
                "key": "sbtrace_region",
                "operator": "=",
                "values": [
                    "south polar cap"
                ]
            }
      ],
    },
    {
        "programs": ["themis"],
    }
]
distances = {
    "space1-space2": 1000
}

In [12]:
#perform search
s = pyaurorax.conjunctions.search(start=start,
                               end=end,
                               ground=ground_params,
                               space=space_params,
                               max_distances=distances,
                               verbose=True)

[2021-06-08 15:04:51.741797] Search object created
[2021-06-08 15:04:51.776090] Request submitted
[2021-06-08 15:04:51.776090] Request ID: 8acf23cc-310e-4011-bd4e-fc326320b3d6
[2021-06-08 15:04:51.776090] Request details available at: http://api.aurorax.space/api/v1/conjunctions/requests/8acf23cc-310e-4011-bd4e-fc326320b3d6
[2021-06-08 15:04:51.776090] Waiting for data ...
[2021-06-08 15:04:52.834226] Checking for data ...
[2021-06-08 15:04:52.903824] Data is now available
[2021-06-08 15:04:52.903824] Retrieving data ...
[2021-06-08 15:04:53.000844] Retrieved 73.1 kB of data containing 12 records

In [13]:
# output data as a pandas dataframe
conjunctions = [c.__dict__ for c in s.data]
df = pd.DataFrame(conjunctions)
df.sort_values("start")

,conjunction_type,start,end,data_sources,min_distance,max_distance,events
6,nbtrace,2019-01-01 08:25:00,2019-01-01 08:25:00,"[{'data_product_metadata_schema': [],\n 'displ...",622.985734,622.985734,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
8,nbtrace,2019-01-01 08:25:00,2019-01-01 08:25:00,"[{'data_product_metadata_schema': [],\n 'displ...",935.831791,935.831791,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
10,nbtrace,2019-01-01 08:25:00,2019-01-01 08:25:00,"[{'data_product_metadata_schema': [],\n 'displ...",853.160622,853.160622,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
7,nbtrace,2019-01-01 10:01:00,2019-01-01 10:01:00,"[{'data_product_metadata_schema': [],\n 'displ...",311.183877,311.183877,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
9,nbtrace,2019-01-01 10:01:00,2019-01-01 10:01:00,"[{'data_product_metadata_schema': [],\n 'displ...",852.345594,852.345594,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
11,nbtrace,2019-01-01 10:01:00,2019-01-01 10:01:00,"[{'data_product_metadata_schema': [],\n 'displ...",716.273324,716.273324,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
0,nbtrace,2019-01-01 10:38:00,2019-01-01 10:38:00,"[{'data_product_metadata_schema': [],\n 'displ...",953.437967,953.437967,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
3,nbtrace,2019-01-01 10:38:00,2019-01-01 10:38:00,"[{'data_product_metadata_schema': [],\n 'displ...",749.914962,749.914962,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
4,nbtrace,2019-01-01 10:38:00,2019-01-01 10:38:00,"[{'data_product_metadata_schema': [],\n 'displ...",761.953037,761.953037,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
1,nbtrace,2019-01-01 12:07:00,2019-01-01 12:09:00,"[{'data_product_metadata_schema': [],\n 'displ...",215.817544,894.794454,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
5,nbtrace,2019-01-01 12:09:00,2019-01-01 12:09:00,"[{'data_product_metadata_schema': [],\n 'displ...",875.857376,875.857376,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."
2,nbtrace,2019-01-01 15:13:00,2019-01-01 15:14:00,"[{'data_product_metadata_schema': [],\n 'displ...",826.483345,974.219774,"[{'conjunction_type': 'nbtrace', 'e1_source': ..."